package cn.online.nocard.web.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGoods<M extends BaseGoods<M>> extends Model<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return get("id");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setStatus(Integer status) {
		set("status", status);
	}

	public Integer getStatus() {
		return get("status");
	}

	public void setMerchId(String merchId) {
		set("merch_id", merchId);
	}

	public String getMerchId() {
		return get("merch_id");
	}

	public void setGoodsName(String goodsName) {
		set("goods_name", goodsName);
	}

	public String getGoodsName() {
		return get("goods_name");
	}

	public void setPicAddress(String picAddress) {
		set("pic_address", picAddress);
	}

	public String getPicAddress() {
		return get("pic_address");
	}

	public void setPrice(Double price) {
		set("price", price);
	}

	public Double getPrice() {
		return get("price");
	}

}
