package cn.online.nocard.web.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAA<M extends BaseAA<M>> extends Model<M> implements IBean {
//
//	public void set(java.lang.String RateName) {
//		set("RateName", RateName);
//	}
//
//	public java.lang.String get() {
//		return get("RateName");
//	}
//
//
//	
//	
//	public void set(java.math.BigDecimal HighLevel) {
//		set("HighLevel", HighLevel);
//	}
//	
//	public java.math.BigDecimal get() {
//		return get("HighLevel");
//	}
//	
//	
//	
//	
//
//	public void set(java.util.Date UpdateTime) {
//		set("UpdateTime", UpdateTime);
//	}
//	
//	public java.util.Date get() {
//		return get("UpdateTime");
//	}
}
