package cn.online.shop.web.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseLog<M extends BaseLog<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setLoginId(java.lang.String loginId) {
		set("loginId", loginId);
	}

	public java.lang.String getLoginId() {
		return get("loginId");
	}
	
	public void setUserName(java.lang.String userName) {
		set("userName", userName);
	}

	public java.lang.String getUserName() {
		return get("userName");
	}

	public void setType(java.lang.String type) {
		set("type", type);
	}

	public java.lang.String getType() {
		return get("type");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public void setDate(java.lang.String date) {
		set("date", date);
	}

	public java.lang.String getDate() {
		return get("date");
	}

	public void setTime(java.lang.String time) {
		set("time", time);
	}

	public java.lang.String getTime() {
		return get("time");
	}

	public void setIp(java.lang.String ip) {
		set("ip", ip);
	}

	public java.lang.String getIp() {
		return get("ip");
	}
	
	public void setOperationObjId(java.lang.String operationObjId) {
		set("operationObjId", operationObjId);
	}
	
	public java.lang.String getOperationObjId() {
		return get("operationObjId");
	}
	
	public void setOperationObjName(java.lang.String operationObjName) {
		set("operationObjName", operationObjName);
	}
	
	public java.lang.String getOperationObjName() {
		return get("operationObjName");
	}
	
	public void setOperationObj(java.lang.String operationObj) {
		set("operationObj", operationObj);
	}
	
	public java.lang.String getOperationObj() {
		return get("operationObj");
	}
	
	public void setDetailId(java.lang.String detailId) {
		set("detailId", detailId);
	}
	
	public java.lang.String getDetailId() {
		return get("detailId");
	}
	
}
