package cn.online.shop.web.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMember<M extends BaseMember<M>> extends Model<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return get("id");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setStatus(Integer status) {
		set("status", status);
	}

	public Integer getStatus() {
		return get("status");
	}

	public void setMemberName(String memberName) {
		set("member_name", memberName);
	}

	public String getMemberName() {
		return get("member_name");
	}

	public void setMemberPhone(Integer memberPhone) {
		set("member_phone", memberPhone);
	}

	public Integer getMemberPhone() {
		return get("member_phone");
	}

	public void setMemberAddress(String memberAddress) {
		set("member_address", memberAddress);
	}

	public String getMemberAddress() {
		return get("member_address");
	}

	public void setWeixinOpenid(String weixinOpenid) {
		set("weixin_openid", weixinOpenid);
	}

	public String getWeixinOpenid() {
		return get("weixin_openid");
	}

}
