package cn.online.shop.web.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOrder<M extends BaseOrder<M>> extends Model<M> implements IBean {

	public void setId(Integer id) {
		set("id", id);
	}

	public Integer getId() {
		return get("id");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setStatus(Integer status) {
		set("status", status);
	}

	public Integer getStatus() {
		return get("status");
	}

	public void setRemark(String remark) {
		set("remark", remark);
	}

	public String getRemark() {
		return get("remark");
	}

	public void setOrderId(String orderId) {
		set("order_id", orderId);
	}

	public String getOrderId() {
		return get("order_id");
	}

	public void setMerchNo(String merchNo) {
		set("merchNo", merchNo);
	}

	public String getMerchNo() {
		return get("merchNo");
	}

	public void setMerchName(String merchName) {
		set("merch_name", merchName);
	}

	public String getMerchName() {
		return get("merch_name");
	}

	public void setMerchPhone(Integer merchPhone) {
		set("merch_phone", merchPhone);
	}

	public Integer getMerchPhone() {
		return get("merch_phone");
	}

	public void setMemberName(String memberName) {
		set("member_name", memberName);
	}

	public String getMemberName() {
		return get("member_name");
	}

	public void setMemberPhone(Integer memberPhone) {
		set("member_phone", memberPhone);
	}

	public Integer getMemberPhone() {
		return get("member_phone");
	}

	public void setMemberAddress(String memberAddress) {
		set("member_address", memberAddress);
	}

	public String getMemberAddress() {
		return get("member_address");
	}

	public void setGoodsNos(String goodsNos) {
		set("goods_nos", goodsNos);
	}

	public String getGoodsNos() {
		return get("goods_nos");
	}

	public void setPrice(Double price) {
		set("price", price);
	}

	public Double getPrice() {
		return get("price");
	}

}
