package main.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("shop_goods", "id", Goods.class);
		arp.addMapping("shop_member", "id", Member.class);
		arp.addMapping("shop_merch", "id", Merch.class);
		arp.addMapping("shop_order", "id", Order.class);
		arp.addMapping("sys_exception_log", "id", SysExceptionLog.class);
		arp.addMapping("sys_log", "id", SysLog.class);
		arp.addMapping("sys_log_detail", "id", SysLogDetail.class);
		arp.addMapping("sys_role", "id", SysRole.class);
		arp.addMapping("sys_source", "id", SysSource.class);
		arp.addMapping("sys_user", "id", SysUser.class);
	}
}

