package main.model;

import cn.hicard.nocard.web.model.base.BaseGoods;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Goods extends BaseGoods<Goods> {
	public static final Goods dao = new Goods();
}
