package main.model;

import cn.hicard.nocard.web.model.base.BaseMember;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Member extends BaseMember<Member> {
	public static final Member dao = new Member();
}
