package main.model;

import cn.hicard.nocard.web.model.base.BaseMerch;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Merch extends BaseMerch<Merch> {
	public static final Merch dao = new Merch();
}
