package main.model;

import cn.hicard.nocard.web.model.base.BaseSysExceptionLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysExceptionLog extends BaseSysExceptionLog<SysExceptionLog> {
	public static final SysExceptionLog dao = new SysExceptionLog();
}
