package main.model;

import cn.hicard.nocard.web.model.base.BaseSysLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysLog extends BaseSysLog<SysLog> {
	public static final SysLog dao = new SysLog();
}
