package main.model;

import cn.hicard.nocard.web.model.base.BaseSysLogDetail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysLogDetail extends BaseSysLogDetail<SysLogDetail> {
	public static final SysLogDetail dao = new SysLogDetail();
}
