package main.model;

import cn.hicard.nocard.web.model.base.BaseSysSource;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysSource extends BaseSysSource<SysSource> {
	public static final SysSource dao = new SysSource();
}
