package cn.hicard.nocard.web.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMember<M extends BaseMember<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public void setMemberName(java.lang.String memberName) {
		set("member_name", memberName);
	}

	public java.lang.String getMemberName() {
		return get("member_name");
	}

	public void setMemberPhone(java.lang.Integer memberPhone) {
		set("member_phone", memberPhone);
	}

	public java.lang.Integer getMemberPhone() {
		return get("member_phone");
	}

	public void setMemberAddress(java.lang.Integer memberAddress) {
		set("member_address", memberAddress);
	}

	public java.lang.Integer getMemberAddress() {
		return get("member_address");
	}

	public void setWeixinOpenid(java.lang.String weixinOpenid) {
		set("weixin_openid", weixinOpenid);
	}

	public java.lang.String getWeixinOpenid() {
		return get("weixin_openid");
	}

}
