package cn.hicard.nocard.web.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysUser<M extends BaseSysUser<M>> extends Model<M> implements IBean {

	public void setUserid(java.lang.String userid) {
		set("userid", userid);
	}

	public java.lang.String getUserid() {
		return get("userid");
	}

	public void setUsername(java.lang.String username) {
		set("username", username);
	}

	public java.lang.String getUsername() {
		return get("username");
	}

	public void setPassword(java.lang.String password) {
		set("password", password);
	}

	public java.lang.String getPassword() {
		return get("password");
	}

	public void setAuthid(java.lang.String authid) {
		set("authid", authid);
	}

	public java.lang.String getAuthid() {
		return get("authid");
	}

	public void setArea(java.lang.String area) {
		set("area", area);
	}

	public java.lang.String getArea() {
		return get("area");
	}

	public void setDepartment(java.lang.String department) {
		set("department", department);
	}

	public java.lang.String getDepartment() {
		return get("department");
	}

	public void setFlagtime(java.lang.String flagtime) {
		set("flagtime", flagtime);
	}

	public java.lang.String getFlagtime() {
		return get("flagtime");
	}

	public void setStartdate(java.lang.String startdate) {
		set("startdate", startdate);
	}

	public java.lang.String getStartdate() {
		return get("startdate");
	}

	public void setEnddate(java.lang.String enddate) {
		set("enddate", enddate);
	}

	public java.lang.String getEnddate() {
		return get("enddate");
	}

	public void setModtime(java.lang.String modtime) {
		set("modtime", modtime);
	}

	public java.lang.String getModtime() {
		return get("modtime");
	}

	public void setAddtime(java.lang.String addtime) {
		set("addtime", addtime);
	}

	public java.lang.String getAddtime() {
		return get("addtime");
	}

	public void setFlag(java.lang.String flag) {
		set("flag", flag);
	}

	public java.lang.String getFlag() {
		return get("flag");
	}

}
