package cn.hicard.nocard.web.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGoods<M extends BaseGoods<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public void setMerchId(java.lang.String merchId) {
		set("merch_id", merchId);
	}

	public java.lang.String getMerchId() {
		return get("merch_id");
	}

	public void setGoodsName(java.lang.String goodsName) {
		set("goods_name", goodsName);
	}

	public java.lang.String getGoodsName() {
		return get("goods_name");
	}

	public void setPicAddress(java.lang.String picAddress) {
		set("pic_address", picAddress);
	}

	public java.lang.String getPicAddress() {
		return get("pic_address");
	}

	public void setPrice(java.lang.Double price) {
		set("price", price);
	}

	public java.lang.Double getPrice() {
		return get("price");
	}

}
