package cn.hicard.nocard.web.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMerch<M extends BaseMerch<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setMerchNo(java.lang.String merchNo) {
		set("merch_no", merchNo);
	}

	public java.lang.String getMerchNo() {
		return get("merch_no");
	}

	public void setMerchName(java.lang.String merchName) {
		set("merch_name", merchName);
	}

	public java.lang.String getMerchName() {
		return get("merch_name");
	}

	public void setMerchPhone(java.lang.Integer merchPhone) {
		set("merch_phone", merchPhone);
	}

	public java.lang.Integer getMerchPhone() {
		return get("merch_phone");
	}

	public void setEmail(java.lang.String email) {
		set("email", email);
	}

	public java.lang.String getEmail() {
		return get("email");
	}

	public void setShopAddress(java.lang.String shopAddress) {
		set("shop_address", shopAddress);
	}

	public java.lang.String getShopAddress() {
		return get("shop_address");
	}

	public void setProvince(java.lang.String province) {
		set("province", province);
	}

	public java.lang.String getProvince() {
		return get("province");
	}

	public void setCity(java.lang.String city) {
		set("city", city);
	}

	public java.lang.String getCity() {
		return get("city");
	}

	public void setArea(java.lang.String area) {
		set("area", area);
	}

	public java.lang.String getArea() {
		return get("area");
	}

	public void setMerchAddress(java.lang.String merchAddress) {
		set("merch_address", merchAddress);
	}

	public java.lang.String getMerchAddress() {
		return get("merch_address");
	}

	public void setRealname(java.lang.String realname) {
		set("realname", realname);
	}

	public java.lang.String getRealname() {
		return get("realname");
	}

	public void setCardNo(java.lang.Integer cardNo) {
		set("card_no", cardNo);
	}

	public java.lang.Integer getCardNo() {
		return get("card_no");
	}

	public void setMerchTypeNo(java.lang.Integer merchTypeNo) {
		set("merch_type_no", merchTypeNo);
	}

	public java.lang.Integer getMerchTypeNo() {
		return get("merch_type_no");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public void setWeixin(java.lang.String weixin) {
		set("weixin", weixin);
	}

	public java.lang.String getWeixin() {
		return get("weixin");
	}

}
