package cn.hicard.nocard.web.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysLogDetail<M extends BaseSysLogDetail<M>> extends Model<M> implements IBean {

	public void setDetailId(java.lang.String detailId) {
		set("detailId", detailId);
	}

	public java.lang.String getDetailId() {
		return get("detailId");
	}

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setOperateTable(java.lang.String operateTable) {
		set("operateTable", operateTable);
	}

	public java.lang.String getOperateTable() {
		return get("operateTable");
	}

	public void setColumn(java.lang.String column) {
		set("column", column);
	}

	public java.lang.String getColumn() {
		return get("column");
	}

	public void setOldValue(java.lang.String oldValue) {
		set("oldValue", oldValue);
	}

	public java.lang.String getOldValue() {
		return get("oldValue");
	}

	public void setNewValue(java.lang.String newValue) {
		set("newValue", newValue);
	}

	public java.lang.String getNewValue() {
		return get("newValue");
	}

	public void setAddTime(java.util.Date AddTime) {
		set("AddTime", AddTime);
	}

	public java.util.Date getAddTime() {
		return get("AddTime");
	}

}
