package cn.hicard.nocard.web.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysExceptionLog<M extends BaseSysExceptionLog<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setActionKey(java.lang.String actionKey) {
		set("actionKey", actionKey);
	}

	public java.lang.String getActionKey() {
		return get("actionKey");
	}

	public void setThrowDate(java.lang.String throwDate) {
		set("throwDate", throwDate);
	}

	public java.lang.String getThrowDate() {
		return get("throwDate");
	}

	public void setThrowTime(java.lang.String throwTime) {
		set("throwTime", throwTime);
	}

	public java.lang.String getThrowTime() {
		return get("throwTime");
	}

	public void setThrowMessage(java.lang.String throwMessage) {
		set("throwMessage", throwMessage);
	}

	public java.lang.String getThrowMessage() {
		return get("throwMessage");
	}

	public void setUserLoginId(java.lang.String userLoginId) {
		set("userLoginId", userLoginId);
	}

	public java.lang.String getUserLoginId() {
		return get("userLoginId");
	}

	public void setUserId(java.lang.Integer userId) {
		set("userId", userId);
	}

	public java.lang.Integer getUserId() {
		return get("userId");
	}

	public void setFrom(java.lang.Integer from) {
		set("from", from);
	}

	public java.lang.Integer getFrom() {
		return get("from");
	}

}
