package cn.hicard.nocard.web.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysUser<M extends BaseSysUser<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setLoginId(java.lang.String loginId) {
		set("loginId", loginId);
	}

	public java.lang.String getLoginId() {
		return get("loginId");
	}

	public void setUserName(java.lang.String userName) {
		set("userName", userName);
	}

	public java.lang.String getUserName() {
		return get("userName");
	}

	public void setPassword(java.lang.String password) {
		set("password", password);
	}

	public java.lang.String getPassword() {
		return get("password");
	}

	public void setArea(java.lang.String area) {
		set("area", area);
	}

	public java.lang.String getArea() {
		return get("area");
	}

	public void setDepartment(java.lang.String department) {
		set("department", department);
	}

	public java.lang.String getDepartment() {
		return get("department");
	}

	public void setUseType(java.lang.String useType) {
		set("useType", useType);
	}

	public java.lang.String getUseType() {
		return get("useType");
	}

	public void setStartDate(java.lang.String startDate) {
		set("startDate", startDate);
	}

	public java.lang.String getStartDate() {
		return get("startDate");
	}

	public void setEndDate(java.lang.String endDate) {
		set("endDate", endDate);
	}

	public java.lang.String getEndDate() {
		return get("endDate");
	}

	public void setOperationTime(java.lang.String operationTime) {
		set("operationTime", operationTime);
	}

	public java.lang.String getOperationTime() {
		return get("operationTime");
	}

	public void setUpdateTime(java.lang.String updateTime) {
		set("updateTime", updateTime);
	}

	public java.lang.String getUpdateTime() {
		return get("updateTime");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}

	public java.lang.String getStatus() {
		return get("status");
	}

	public void setRoleId(java.lang.String roleId) {
		set("roleId", roleId);
	}

	public java.lang.String getRoleId() {
		return get("roleId");
	}

}
