package cn.hicard.nocard.web.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGoods<M extends BaseGoods<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public void setMerchId(java.lang.String merchId) {
		set("merch_id", merchId);
	}

	public java.lang.String getMerchId() {
		return get("merch_id");
	}

	public void setGoodsNo(java.lang.String goodsNo) {
		set("goods_no", goodsNo);
	}

	public java.lang.String getGoodsNo() {
		return get("goods_no");
	}

	public void setGoodsName(java.lang.String goodsName) {
		set("goods_name", goodsName);
	}

	public java.lang.String getGoodsName() {
		return get("goods_name");
	}

	public void setPrice(java.lang.Double price) {
		set("price", price);
	}

	public java.lang.Double getPrice() {
		return get("price");
	}

	public void setPicAddress1(java.lang.String picAddress1) {
		set("pic_address1", picAddress1);
	}

	public java.lang.String getPicAddress1() {
		return get("pic_address1");
	}

	public void setPicAddress2(java.lang.String picAddress2) {
		set("pic_address2", picAddress2);
	}

	public java.lang.String getPicAddress2() {
		return get("pic_address2");
	}

	public void setPicAddress3(java.lang.String picAddress3) {
		set("pic_address3", picAddress3);
	}

	public java.lang.String getPicAddress3() {
		return get("pic_address3");
	}

	public void setSort(java.lang.Integer sort) {
		set("sort", sort);
	}

	public java.lang.Integer getSort() {
		return get("sort");
	}

}
