package cn.online.shop.web.model;

import cn.online.shop.web.model.base.BaseGoods;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Goods extends BaseGoods<Goods> {
	public static final Goods dao = new Goods();

}
