package cn.online.nocard.web.model;

import cn.es.common.ESSearchCondition;
import cn.es.utils.ESSQLHelper;
import cn.online.nocard.web.model.base.BaseGoods;
import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Page;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Goods extends BaseGoods<Goods> {
	public static final Goods dao = new Goods();

	/**
	 * 分页查询
	 * @param sc
	 * @return
	 */
	public List<Goods> searchMerchGoodsList(ESSearchCondition sc){
		int pageNumber = sc.page.getIndex();
		int pageSize = sc.page.getSize();

		ESSQLHelper sql = new ESSQLHelper(" from  t_goods  WHERE 1 = 1");
		sql.equals("MerchId", sc.getString("MerchId"));
		sql.orderBy(sc,"update_time", "desc");
		return super.find("select *"+sql.toString(),sql.getParams());
	}
//
//	public Goods searchByGoodsName(String GoodsName){
//		return super.findFirst("SELECT * FROM sys_Goods WHERE GoodsName = ?", GoodsName);
//	}
//
//	/**
//	 * 根据用户登录ID查询
//	 * @param loginId
//	 * @return
//	 */
//	public Goods searchByloginId(String loginId){
//		return super.findFirst("select * from sys_Goods where loginId = ?",loginId);
//	}
//
//	public boolean batchDelete(Object... ids){
//		ESSQLHelper sql = new ESSQLHelper("DELETE FROM sys_Goods WHERE 1 = 1");
//		sql.in("id", ids);
//		return Db.update(sql.toString(), sql.getParams()) > 0;
//	}
//
//	public boolean batchSetNullRoleIdByRoleId(Object...roleIds){
//		ESSQLHelper sql = new ESSQLHelper("UPDATE sys_Goods set roleId = null WHERE 1 = 1");
//		sql.in("roleId", roleIds);
//		return Db.update(sql.toString(), sql.getParams()) > 0;
//	}
}
