package cn.online.nocard.web.model;

import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Page;

import cn.es.common.ESSearchCondition;
import cn.es.utils.ESSQLHelper;
import cn.online.nocard.web.model.base.BaseUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class User extends BaseUser<User> {
	public static final User dao = new User();
	
	/**
	 * 分页查询
	 * @param sc
	 * @return
	 */
	public Page<User> search(ESSearchCondition sc){
		int pageNumber = sc.page.getIndex();
		int pageSize = sc.page.getSize();
		
		ESSQLHelper sql = new ESSQLHelper(" from (select u.*,r.roleName FROM sys_user u left join sys_role r on (u.roleId = r.id)) temp  WHERE 1 = 1");
		sql.equals("loginId", sc.getString("loginId"));
		sql.equals("userName", sc.getString("userName"));
		sql.notEquals("loginId", "admin");
		sql.equals("status", sc.getString("status"));
		sql.orderBy(sc,"updateTime", "desc");
		return super.paginate(pageNumber, pageSize, "select *", sql.toString(),sql.getParams());
	}
	
	public User searchByUserName(String userName){
		return super.findFirst("SELECT * FROM sys_user WHERE userName = ?", userName);
	}
	
	/**
	 * 根据用户登录ID查询
	 * @param loginId
	 * @return
	 */
	public User searchByloginId(String loginId){
		return super.findFirst("select * from sys_user where loginId = ?",loginId);
	}
	
	public boolean batchDelete(Object... ids){
		ESSQLHelper sql = new ESSQLHelper("DELETE FROM sys_user WHERE 1 = 1");
		sql.in("id", ids);
		return Db.update(sql.toString(), sql.getParams()) > 0;
	}
	
	public boolean batchSetNullRoleIdByRoleId(Object...roleIds){
		ESSQLHelper sql = new ESSQLHelper("UPDATE sys_user set roleId = null WHERE 1 = 1");
		sql.in("roleId", roleIds);
		return Db.update(sql.toString(), sql.getParams()) > 0;
	}
}
